site_name: nmsd.xyz
site_url: https://nmsd.xyz
site_author: Nima Saed
extra:
  homepage: https://nmsd.xyz

theme:
  icon:
    logo: bootstrap/shield
  favicon: favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  name: material
  palette:
    primary: custom
    accent: blue
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true


# Footer
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nimasaed/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.nl/@nima
    - icon: fontawesome/brands/github
      link: https://github.com/nimasaed
  generator: false

copyright: Copyright &copy; 2019 - 2024 Nima Saed

# pages
nav:
  - 'About': 'index.md'
  - 'Resume':
    - 'Education and publications': 'resume/education.md'
    - 'Professional Experience': 'resume/professional_experience.md'
    - 'Others' : 'resume/other.md'
  - 'Blog':
    - '2023':
      - 'Enabling Touch ID for sudo ': 'blog/sudo-with-touch-id-on-Mac.md'
    - '2021':
      - 'AWS Profile Changer': 'blog/AWS-Profile-changer.md'
    - '2019':
      - 'MSF on Docker': 'blog/Metasploit-Framework-console.md'
  - 'Notes':
    - 'Secure Homelab':
      - 'Reverse Proxy (Traefik)': 'notes/traefik.md'
      - 'Podman and Systemd': 'notes/podman-systemd.md'
      - 'Authentication': 'notes/authelia.md'
      - 'Homepage': 'notes/homepage.md'
    - 'Languages':
      - 'Bash Tips': 'notes/bash-tips.md'
  - 'Talks':
    - '2025':
      - 'Hot Plastic, Cool Stuff' : 'talks/hot_plastic_cool_stuff.md'
    - '2024':
      - 'Authorization Engine': 'talks/authorization_engine.md'
